'use client';
import { useEffect, useRef, useState } from 'react';
import { ArrowDownToLine, ArrowUpRight, Check, CircleHelp, Crosshair, Hand, Minus, MousePointer2, Pause, PenTool, Play, Plus, Redo2, RotateCcw, Shuffle, Sparkles, Undo2, X } from 'lucide-react';
import { Slider } from '@/components/ui/slider';
import { Switch } from '@/components/ui/switch';
import { DEFAULTS, PALETTES, renderStroke, resample, type Brush, type Stroke } from '@/lib/brush-engine';
import { useBrushCanvas } from '@/hooks/use-brush-canvas';

const BRUSHES: { id: Brush; number: string; title: string; caption: string; tag: string }[] = [
  { id:'subway',number:'01',title:'NYC subway lines',caption:'A city, in a single stroke.',tag:'CARTOGRAPHY' },
  { id:'figures',number:'02',title:'Little figures',caption:'Life between the lines.',tag:'ARCHITECTURE' },
  { id:'gunpla',number:'03',title:'Gunpla components',caption:'An assembly of possibilities.',tag:'MODEL MAKING' },
];
function BrushPreview({brush}:{brush:Brush}) {
  const ref=useRef<HTMLCanvasElement>(null);
  useEffect(()=>{const c=ref.current?.getContext('2d');if(!c)return;c.clearRect(0,0,440,150);c.save();c.scale(2,2);const s:Stroke={id:1,brush,seed:12,settings:{...DEFAULTS,size:brush==='subway'?.7:brush==='figures'?.8:.63,labels:false,lines:3,density:.8},points:resample([{x:15,y:48},{x:45,y:48},{x:65,y:25},{x:100,y:25},{x:122,y:47},{x:156,y:47},{x:180,y:27},{x:207,y:27}],3)};if(brush==='figures')s.points=resample([{x:16,y:58},{x:210,y:58}],4);if(brush==='gunpla')s.points=resample([{x:23,y:41},{x:200,y:41}],3);renderStroke(c,s);c.restore();},[brush]);
  return <canvas ref={ref} width={440} height={150} aria-hidden="true"/>;
}
function RangeControl({label,value,min,max,onChange}:{label:string;value:number;min:number;max:number;onChange:(n:number)=>void}) {
  return <div className="range-control"><div className="control-label"><span>{label}</span><output>{value.toFixed(2)}×</output></div><Slider aria-label={label} value={[value]} min={min} max={max} step={.05} onValueChange={v=>onChange(Array.isArray(v)?v[0]:v)}/></div>;
}
export default function Home() {
  const a=useBrushCanvas(),[help,setHelp]=useState(false),dialog=useRef<HTMLDialogElement>(null);
  const current=BRUSHES.find(b=>b.id===a.brush)!;
  useEffect(()=>{if(help)dialog.current?.showModal();else dialog.current?.close();},[help]);
  return <main className="studio">
    <header className="topbar"><a className="wordmark" href="/" aria-label="Brush Atlas home"><span className="brand-symbol"><i/><i/><i/></span>BRUSH<span className="wordmark-light">ATLAS</span><span className="edition">®</span></a><div className="topbar-caption">AN EXPERIMENT IN GENERATIVE DRAWING</div><div className="topbar-right"><span className="live-dot"/>PLAYGROUND <span className="version">V.01</span><button className="help-button" aria-label="How to use Brush Atlas" onClick={()=>setHelp(true)}><CircleHelp size={18}/></button></div></header>
    <div className="workspace">
      <aside className="library"><div className="section-eyebrow"><span>THE BRUSH LIBRARY</span><span>03</span></div><h1>Ordinary things.<br/><em>Extraordinary lines.</em></h1><p className="library-intro">Pick a brush. Make your own world.</p>
        <div className="brush-list" role="group" aria-label="Brush library">{BRUSHES.map(b=><button key={b.id} className={`brush-card ${a.brush===b.id?'selected':''}`} onClick={()=>{a.setBrush(b.id);a.setMode('draw');}} aria-pressed={a.brush===b.id}><div className="brush-card-meta"><span>{b.number} / {b.tag}</span><span className="selected-mark">{a.brush===b.id?<ArrowUpRight size={15}/>:<Plus size={14}/>}</span></div><BrushPreview brush={b.id}/><div className="brush-name">{b.title}</div><p>{b.caption}</p></button>)}</div>
        <div className="library-note"><span className="small-cross">✳</span><p>Not just a brush.<br/>A little system of its own.</p></div><div className="library-foot">DESIGNED TO WANDER.</div>
      </aside>
      <section className="drawing-area" aria-label="Drawing workspace"><div className="canvas-heading"><span><span className="live-dot"/>{a.demo?'COMPOSING':a.playing?'LIVE CANVAS':'PAUSED'}</span><span className="canvas-sheet">UNTITLED — {String(a.strokes.length).padStart(2,'0')} STROKES</span><button className="text-button" onClick={()=>a.setPlaying(p=>!p)}>{a.playing?<Pause size={13}/>:<Play size={13}/>}<span>{a.playing?'Pause':'Play'}</span></button></div>
        <div className={`canvas-host ${a.mode==='pan'?'pan-mode':''}`} ref={a.container}>
          <canvas ref={a.canvas} className="drawing-canvas" aria-label="Interactive drawing canvas. Drag to draw. Use Auto-compose for a keyboard-accessible drawing." onPointerDown={a.onPointerDown} onPointerMove={a.onPointerMove} onPointerUp={a.onPointerUp} onPointerCancel={a.onPointerUp} onLostPointerCapture={a.onPointerUp} tabIndex={0}/>
          <span className="corner tl"/><span className="corner tr"/><span className="corner bl"/><span className="corner br"/>
          <div className="canvas-title"><span>EXPERIMENT {current.number}</span><h2>{current.title}<span>↗</span></h2><p>{a.brush==='subway'?'New routes. No wrong turns.':a.brush==='figures'?'A small cast. An infinite city.':'Every part has a place.'}</p></div>
          <div className="canvas-scale"><span>0</span><i/><span>100</span><small>{a.brush==='subway'?'IMAGINARY MILES':a.brush==='figures'?'PEOPLE / ELEVATION':'PARTS / ASSEMBLY'}</small></div>
          {a.strokes.length===0&&<div className="empty-prompt"><PenTool size={28}/><p>Your next world starts here.</p><span>Click and drag to draw, or try Auto-compose.</span></div>}
          <div className="canvas-hint"><MousePointer2 size={13}/><span>{a.mode==='pan'?'Drag to move around':'Click & drag anywhere to draw'}</span></div>
          <div className="floating-tools"><div className="tool-pair"><button aria-label="Draw (B)" title="Draw (B)" className={a.mode==='draw'?'active':''} onClick={()=>a.setMode('draw')}><PenTool size={17}/></button><button aria-label="Pan (H)" title="Pan (H)" className={a.mode==='pan'?'active':''} onClick={()=>a.setMode('pan')}><Hand size={17}/></button></div><span className="tool-divider"/><button aria-label="Undo" title="Undo (Ctrl/⌘ Z)" disabled={!a.canUndo} onClick={a.undo}><Undo2 size={17}/></button><button aria-label="Redo" title="Redo (Ctrl/⌘ Shift Z)" disabled={!a.canRedo} onClick={a.redo}><Redo2 size={17}/></button><span className="tool-divider"/><button aria-label="Zoom out" disabled={a.zoom<=.5} onClick={()=>a.setZoom(z=>Math.max(.5,z-.25))}><Minus size={15}/></button><button className="zoom-readout" onClick={a.resetView} title="Fit to canvas (0)">{Math.round(a.zoom*100)}%</button><button aria-label="Zoom in" disabled={a.zoom>=2} onClick={()=>a.setZoom(z=>Math.min(2,z+.25))}><Plus size={15}/></button><button aria-label="Fit canvas" onClick={a.resetView}><Crosshair size={16}/></button></div>
        </div><footer className="canvas-footer"><span><span className="status-dot"/>READY TO EXPLORE</span><span className="coordinates">X {String(a.position.x).padStart(4,'0')} <b>/</b> Y {String(a.position.y).padStart(4,'0')}</span><span>MADE OF POSSIBILITIES</span></footer>
      </section>
      <aside className="inspector"><div className="section-eyebrow"><span>BRUSH SETTINGS</span><button aria-label="Reset brush settings" title="Reset brush settings" onClick={()=>{a.setSettings({...DEFAULTS});a.setNotice('Brush settings reset');}}><RotateCcw size={14}/></button></div><div className="inspector-title"><span className="brush-index">{current.number}</span><div><h2>{current.title}</h2><span>PROCEDURAL BRUSH</span></div></div>
        <section className="settings-group"><RangeControl label="Brush size" value={a.settings.size} min={.5} max={2} onChange={v=>a.update('size',v)}/><RangeControl label="Density" value={a.settings.density} min={.4} max={1.8} onChange={v=>a.update('density',v)}/><RangeControl label={a.brush==='subway'?'Route spread':a.brush==='figures'?'Figure detail':'Part detail'} value={a.brush==='subway'?a.settings.spread:a.settings.detail} min={.5} max={1.8} onChange={v=>a.update(a.brush==='subway'?'spread':'detail',v)}/></section>
        <section className="settings-group palette-group"><div className="control-label"><span>{a.brush==='subway'?'Route palette':'Ink palette'}</span><span className="tiny-label">{a.settings.color===-1?'ORIGINAL':'SINGLE INK'}</span></div><div className="palette"><button aria-label="Original palette" aria-pressed={a.settings.color===-1} className={`swatch multi ${a.settings.color===-1?'chosen':''}`} onClick={()=>a.update('color',-1)}>{a.settings.color===-1&&<Check size={13}/>}</button>{PALETTES.map((color,i)=><button key={color} aria-label={['Jade','Vermilion','Ochre','Blue','Violet','Graphite'][i]} aria-pressed={a.settings.color===i} className={`swatch ${a.settings.color===i?'chosen':''}`} style={{backgroundColor:color}} onClick={()=>a.update('color',i)}>{a.settings.color===i&&<Check size={13}/>}</button>)}</div><p>{a.settings.color<0?a.brush==='subway'?'A little New York, all mixed up.':a.brush==='figures'?'The quiet blue of an architect’s pen.':'Technical ink, straight off the runner.':'One color. A different character.'}</p></section>
        {a.brush==='subway'&&<section className="settings-group"><div className="control-label"><span>Parallel routes</span><span className="tiny-label">{a.settings.lines} LINES</span></div><div className="route-options" role="group" aria-label="Number of parallel routes">{[1,2,3,4,5].map(n=><button key={n} aria-pressed={a.settings.lines===n} className={a.settings.lines===n?'chosen':''} onClick={()=>a.update('lines',n)}>{n}</button>)}</div></section>}
        <section className="settings-group toggle-group"><label><span>{a.brush==='subway'?'Station labels':a.brush==='figures'?'Figure numbers':'Part numbers'}</span><Switch checked={a.settings.labels} onCheckedChange={v=>a.update('labels',v)}/></label><label><span>Dot grid</span><Switch checked={a.grid} onCheckedChange={a.setGrid}/></label><label><span>Live motion</span><Switch checked={a.playing} onCheckedChange={a.setPlaying}/></label></section>
        <div className="compose-actions"><button className="primary-button" onClick={()=>a.compose()}><Sparkles size={16}/>Auto-compose<ArrowUpRight size={15}/></button><button className="secondary-button" onClick={()=>a.compose(false)}><Shuffle size={15}/>New variation</button><p>Settings shape your next stroke.<br/>Auto-compose to try them on a full drawing.</p></div>
        <div className="inspector-bottom"><button className="clear-button" disabled={!a.strokes.length} onClick={a.clear}><X size={14}/>Clear canvas</button><button className="export-button" onClick={a.exportImage}><ArrowDownToLine size={15}/>Export PNG</button></div>
      </aside>
    </div>
    {a.notice&&<div className="toast" role="status"><Check size={15}/>{a.notice}</div>}
    <dialog ref={dialog} className="help-panel" onCancel={()=>setHelp(false)} onClick={e=>{if(e.target===e.currentTarget)setHelp(false);}} aria-labelledby="help-title"><button className="help-close" aria-label="Close instructions" onClick={()=>setHelp(false)}><X size={20}/></button><span className="section-eyebrow">A FIELD GUIDE</span><h2 id="help-title">Follow your curiosity.</h2><p>Choose a brush and drag across the canvas. Mix all three brushes in the same drawing. Each gesture builds a new, slightly unexpected structure.</p><p>Auto-compose makes a complete drawing with your current settings. Clear and auto-compose can both be undone. PNG export saves the full drawing sheet without the grid.</p><div className="shortcut-list">{[['1 / 2 / 3','Choose a brush'],['B / H','Draw / move canvas'],['Space','Pause / play motion'],['Ctrl / ⌘ Z','Undo'],['Ctrl / ⌘ Shift Z','Redo'],['0','Fit canvas']].map(([key,label])=><div key={key}><span>{label}</span><kbd>{key}</kbd></div>)}</div><p className="help-note">Subway drawings are imaginary compositions, not navigation maps. Gunpla parts are original procedural studies.</p></dialog>
  </main>;
}
